### ISSUE TITLE
Grade Comments

### ISSUE THREAD

**Issue by aclavin-eab** [thenuttyirishman/Train-Scheduler#1]
NO README TEXT?!?! Empty css file, it looks fine so if you don't have any css just don't include a file for it.

The javascript works, looks nice enough. Var is declared not at the top of the outer most scope in the file, it should be declared up top with no value, and then set to the value it is set to on the line you have it, instead of declared and set on that same line.

NO ALERTS, try to remember to remove these and the console.logs

**Comment by thenuttyirishman** [comment]
Yes I did forget the read me. I wont make that mistake again. I planned on adding some css but I didnt have enough time. Thank you for all the comments I appreciate the feedback
